### ISSUE TITLE
Load testing and got {:error, %HTTPoison.Error{id: nil, reason: :connect_timeout}}

### ISSUE THREAD

**Issue by dimun** [edgurgel/httpoison#291]
I'm doing some load tests with [locust](https://locust.io/), my software has a gateway for doing HTTP request in several servers, i'm using HTTPoison in the gateway, but when I got an error for connect_timeout (because of the amount of requests), each single request throw this error `{:error, %HTTPoison.Error{id: nil, reason: :connect_timeout}}`, even after stopping the locust test, the only way for recovering the gateway is by restarting the gateway server.

If anybody can help me, thank you in advance.

**Comment by dannote** [comment]
benoitc/hackney#420 has been fixed recently. Bumping `hackney` to 1.10.1 should help.

**Comment by dannote** [comment]
@edgurgel could you please?

**Comment by edgurgel** [comment]
I think you can do `mix deps.update hackney` you should be able to download the newest hackney.

**Comment by edgurgel** [comment]
@dimun, having the newest hackney solved the issues you were noticing?

**Comment by svileng** [comment]
I updated Hackney to `1.10.1`, after reading this thread, and sadly I'm still experiencing this issue. My case is not during load testing, but in a production environment. I send at least 300 HTTP requests every 2 minutes to various API servers and I often I`%HTTPoison.Error{id: nil, reason: :connect_timeout}`, even straight after a restart, and the error seems to persist until another restart, which is not great... Any thoughts? 😞

**Comment by dimun** [comment]
@edgurgel, the first thing that I've done is to change the phoenix environment by `prod` and that improved the amount of simultaneous users but the error still happened, so I had to change the library, but now that I saw this answer, I've mounted the previous version with httpoison and updated the hackney version and it worked for me. thank you

**Comment by svileng** [comment]
FWIW: To quote the person from the Hackney issue thread (above):

> For reference, I noticed the problems still occurs but the fix here means hackney now actually recovers.

Although the error happens for me, still, it does not persist, so as long as you retry your request, it's all good. So upgrading to `1.10.1` is a big improvement.

**Comment by dsignr** [comment]
This issue unfortunately still persists on production while using Httpoison. Upgrading to Hackney 1.10.1 did reduce the frequency of timeouts, nevertheless, it still happens. Retrying requests isn't really a valid solution, atleast not for me because we're using this for our orders on our store with PayPal API and we got a handful of users complaining that their payment failed. And their API legitimately times out sometimes and we want to be able to track that. With Httpoison/Hackney timing out randomly, it makes it harder to discern between the library and the real API timeouts. Having that said, Hackney hit 1.0 only like 2 days ago, so I'm going to give this some more time and see where it goes as its unreasonable of me to expect the author to adhere to my personal urgency. Not switching libs as we've invested lots of code w/ Httpoison and also, I love this lib :)

**Comment by edgurgel** [comment]
Have you checked hackney metrics? It may give us more info why this is happening. It tracks number of connections, requests, etc, etc. You may find the reason why you are seeing so many connection timeouts. Maybe the pool is queuing your requests or something like this and it may need some tweaking on the options.  https://github.com/benoitc/hackney#metrics

**Comment by dsignr** [comment]
@edgurgel Wow, thank you very much, I hadn't looked into those options (or anything beyond Httpoison's own options). Thank you :)
